version: '2.2'
services:
  mariadb:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: tracexdb2022
      MARIADB_DATABASE: tracex
  tracex:
    depends_on:
      - mariadb
    image: tracex-application:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.jpa.database-platform" : "org.hibernate.dialect.MariaDBDialect",
            "spring.jpa.show-sql" : "true",
            "spring.jpa.hibernate.ddl-auto" : "udpate",
            "spring.jpa.hibernate.naming.physical-strategy" : "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl",
            "spring.datasource.type" : "com.zaxxer.hikari.HikariDataSource",
            "spring.datasource.url" : "jdbc:mariadb://mariadb/tracex?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_bin",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "tracexdb2022",
            "spring.datasource.driverClassName" : "org.mariadb.jdbc.Driver",
            "spring.datasource.hikari.idle-timeout" : "60000",
            "spring.datasource.hikari.maximum-pool-size" : "5",
            "springdoc.api-docs.path" : "/api-docs"
          }'
volumes:
  db_data:
