version: '2.2'
services:
  mariadb:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: tracexdb2022
      MARIADB_DATABASE: tracex
  tracex:
    depends_on:
      - mariadb
    image: tracex-application:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url" : "jdbc:mariadb://mariadb/tracex?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8_bin",
            "spring.datasource.password" : "tracexdb2022"
          }'
volumes:
  db_data:
